# Generated by Django 4.0 on 2021-12-21 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.hall'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.row'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.seat'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
