# Generated by Django 4.0 on 2021-12-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_rename_lat_cinema_latitude_and_more'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
        ),
    ]
