# Generated by Django 4.0 on 2021-12-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_hall_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='row',
            name='seat_map',
        ),
        migrations.DeleteModel(
            name='Seats',
        ),
    ]
