# Generated by Django 4.0 on 2021-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_row_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
