# Generated by Django 4.0 on 2021-12-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_hall_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='dolbyAtmos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hall',
            name='threeD',
            field=models.BooleanField(default=False),
        ),
    ]
