# Generated by Django 4.0 on 2021-12-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_origin', models.CharField(max_length=255, null=True)),
                ('name_rus', models.CharField(max_length=255, null=True)),
                ('large_img', models.CharField(max_length=1000, null=True)),
                ('medium_img', models.CharField(max_length=1000, null=True)),
                ('small_img', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
                ('rating', models.FloatField()),
                ('age_restriction', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
