# Generated by Django 4.0 on 2021-12-19 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('originalName', models.CharField(max_length=255, null=True)),
                ('image_small', models.CharField(max_length=1000, null=True)),
                ('image_large', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('originalName', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('originalName', models.CharField(max_length=255, null=True)),
                ('image_small', models.CharField(max_length=1000, null=True)),
                ('image_large', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('name_origin', models.CharField(max_length=255, null=True)),
                ('name_rus', models.CharField(max_length=255, null=True)),
                ('large_img', models.CharField(max_length=1000, null=True)),
                ('medium_img', models.CharField(max_length=1000, null=True)),
                ('small_img', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(null=True)),
                ('rating', models.FloatField()),
                ('age_restriction', models.IntegerField()),
                ('duriation', models.BigIntegerField()),
                ('start_date', models.DateField(blank=True)),
                ('finish_date', models.DateField(null=True)),
                ('actors', models.ManyToManyField(blank=True, to='films.Actor')),
                ('countries', models.ManyToManyField(blank=True, to='films.County')),
                ('directors', models.ManyToManyField(blank=True, to='films.Director')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_eng', models.CharField(default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
        migrations.CreateModel(
            name='Posters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_large', models.CharField(blank=True, max_length=1000, null=True)),
                ('poster_small', models.CharField(blank=True, max_length=1000, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, to='films.Genres'),
        ),
    ]
