# Generated by Django 4.0 on 2021-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='finish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
