# Generated by Django 4.0 on 2021-12-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_finish_date_film_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
