# Generated by Django 4.0 on 2021-12-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_film_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='trailer_url',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='film',
        ),
        migrations.AddField(
            model_name='film',
            name='trailers',
            field=models.ManyToManyField(blank=True, to='films.Trailer'),
        ),
        migrations.DeleteModel(
            name='Posters',
        ),
    ]
