# Generated by Django 4.0 on 2021-12-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_trailer_posters'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(null=True, to='films.Genres'),
        ),
    ]
