# Generated by Django 4.0 on 2021-12-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_film_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genres',
            old_name='name',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='genres',
            name='title_eng',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, to='films.Genres'),
        ),
    ]
