# Generated by Django 4.0 on 2021-12-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='cinema',
            old_name='long',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='cinema',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
