# Generated by Django 4.0 on 2021-12-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_finish_date_alter_film_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
